version: '3'

services:
  postgres_db:
    image: "postgres"
    container_name: postgres_db
    network_mode: bridge
    ports:
      - '5432:5432'
    env_file:
      - database.env # configure postgres  
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      
volumes:
  postgresql_data:
  
