spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:pilot}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    hikari:
      connection-timeout: ${HIKARI_TIMEOUT:20000}
      maximum-pool-size: ${HIKARI_POOL_SIZE:5}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
      show-sql: true
  flyway:
    enabled: true
    schemas: marvel
